# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ConfPersonPT(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, description=None, first_name=None, id=None, last_name=None, network_id=None):
        """
        ConfPersonPT - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'description': 'str',
            'first_name': 'str',
            'id': 'int',
            'last_name': 'str',
            'network_id': 'int'
        }

        self.attribute_map = {
            'description': 'description',
            'first_name': 'firstName',
            'id': 'id',
            'last_name': 'lastName',
            'network_id': 'networkId'
        }

        self._description = description
        self._first_name = first_name
        self._id = id
        self._last_name = last_name
        self._network_id = network_id

    @property
    def description(self):
        """
        Gets the description of this ConfPersonPT.

        :return: The description of this ConfPersonPT.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this ConfPersonPT.

        :param description: The description of this ConfPersonPT.
        :type: str
        """

        self._description = description

    @property
    def first_name(self):
        """
        Gets the first_name of this ConfPersonPT.

        :return: The first_name of this ConfPersonPT.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this ConfPersonPT.

        :param first_name: The first_name of this ConfPersonPT.
        :type: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")

        self._first_name = first_name

    @property
    def id(self):
        """
        Gets the id of this ConfPersonPT.

        :return: The id of this ConfPersonPT.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ConfPersonPT.

        :param id: The id of this ConfPersonPT.
        :type: int
        """

        self._id = id

    @property
    def last_name(self):
        """
        Gets the last_name of this ConfPersonPT.

        :return: The last_name of this ConfPersonPT.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this ConfPersonPT.

        :param last_name: The last_name of this ConfPersonPT.
        :type: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")

        self._last_name = last_name

    @property
    def network_id(self):
        """
        Gets the network_id of this ConfPersonPT.

        :return: The network_id of this ConfPersonPT.
        :rtype: int
        """
        return self._network_id

    @network_id.setter
    def network_id(self, network_id):
        """
        Sets the network_id of this ConfPersonPT.

        :param network_id: The network_id of this ConfPersonPT.
        :type: int
        """

        self._network_id = network_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ConfPersonPT):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
