# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CorNetwork(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, active=None, description=None, id=None, name=None, network_users=None, shortcut=None):
        """
        CorNetwork - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'active': 'bool',
            'description': 'str',
            'id': 'int',
            'name': 'str',
            'network_users': 'CorUser',
            'shortcut': 'str'
        }

        self.attribute_map = {
            'active': 'active',
            'description': 'description',
            'id': 'id',
            'name': 'name',
            'network_users': 'networkUsers',
            'shortcut': 'shortcut'
        }

        self._active = active
        self._description = description
        self._id = id
        self._name = name
        self._network_users = network_users
        self._shortcut = shortcut

    @property
    def active(self):
        """
        Gets the active of this CorNetwork.

        :return: The active of this CorNetwork.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """
        Sets the active of this CorNetwork.

        :param active: The active of this CorNetwork.
        :type: bool
        """

        self._active = active

    @property
    def description(self):
        """
        Gets the description of this CorNetwork.

        :return: The description of this CorNetwork.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this CorNetwork.

        :param description: The description of this CorNetwork.
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """
        Gets the id of this CorNetwork.

        :return: The id of this CorNetwork.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CorNetwork.

        :param id: The id of this CorNetwork.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this CorNetwork.

        :return: The name of this CorNetwork.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CorNetwork.

        :param name: The name of this CorNetwork.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) > 100:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")
        if name is not None and len(name) < 0:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")

        self._name = name

    @property
    def network_users(self):
        """
        Gets the network_users of this CorNetwork.

        :return: The network_users of this CorNetwork.
        :rtype: CorUser
        """
        return self._network_users

    @network_users.setter
    def network_users(self, network_users):
        """
        Sets the network_users of this CorNetwork.

        :param network_users: The network_users of this CorNetwork.
        :type: CorUser
        """

        self._network_users = network_users

    @property
    def shortcut(self):
        """
        Gets the shortcut of this CorNetwork.

        :return: The shortcut of this CorNetwork.
        :rtype: str
        """
        return self._shortcut

    @shortcut.setter
    def shortcut(self, shortcut):
        """
        Sets the shortcut of this CorNetwork.

        :param shortcut: The shortcut of this CorNetwork.
        :type: str
        """
        if shortcut is None:
            raise ValueError("Invalid value for `shortcut`, must not be `None`")
        if shortcut is not None and len(shortcut) > 100:
            raise ValueError("Invalid value for `shortcut`, length must be less than or equal to `100`")
        if shortcut is not None and len(shortcut) < 0:
            raise ValueError("Invalid value for `shortcut`, length must be greater than or equal to `0`")

        self._shortcut = shortcut

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CorNetwork):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
