# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CoreUserPT(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, activated=None, authorities=None, channel=None, email=None, first_name=None, id=None, imageurl=None, lang_key=None, last_name=None, login=None, network=None):
        """
        CoreUserPT - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'activated': 'bool',
            'authorities': 'list[str]',
            'channel': 'list[CoreChannelPT]',
            'email': 'str',
            'first_name': 'str',
            'id': 'int',
            'imageurl': 'str',
            'lang_key': 'str',
            'last_name': 'str',
            'login': 'str',
            'network': 'CoreNetworkPT'
        }

        self.attribute_map = {
            'activated': 'activated',
            'authorities': 'authorities',
            'channel': 'channel',
            'email': 'email',
            'first_name': 'firstName',
            'id': 'id',
            'imageurl': 'imageurl',
            'lang_key': 'langKey',
            'last_name': 'lastName',
            'login': 'login',
            'network': 'network'
        }

        self._activated = activated
        self._authorities = authorities
        self._channel = channel
        self._email = email
        self._first_name = first_name
        self._id = id
        self._imageurl = imageurl
        self._lang_key = lang_key
        self._last_name = last_name
        self._login = login
        self._network = network

    @property
    def activated(self):
        """
        Gets the activated of this CoreUserPT.

        :return: The activated of this CoreUserPT.
        :rtype: bool
        """
        return self._activated

    @activated.setter
    def activated(self, activated):
        """
        Sets the activated of this CoreUserPT.

        :param activated: The activated of this CoreUserPT.
        :type: bool
        """

        self._activated = activated

    @property
    def authorities(self):
        """
        Gets the authorities of this CoreUserPT.

        :return: The authorities of this CoreUserPT.
        :rtype: list[str]
        """
        return self._authorities

    @authorities.setter
    def authorities(self, authorities):
        """
        Sets the authorities of this CoreUserPT.

        :param authorities: The authorities of this CoreUserPT.
        :type: list[str]
        """

        self._authorities = authorities

    @property
    def channel(self):
        """
        Gets the channel of this CoreUserPT.

        :return: The channel of this CoreUserPT.
        :rtype: list[CoreChannelPT]
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """
        Sets the channel of this CoreUserPT.

        :param channel: The channel of this CoreUserPT.
        :type: list[CoreChannelPT]
        """

        self._channel = channel

    @property
    def email(self):
        """
        Gets the email of this CoreUserPT.

        :return: The email of this CoreUserPT.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this CoreUserPT.

        :param email: The email of this CoreUserPT.
        :type: str
        """

        self._email = email

    @property
    def first_name(self):
        """
        Gets the first_name of this CoreUserPT.

        :return: The first_name of this CoreUserPT.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """
        Sets the first_name of this CoreUserPT.

        :param first_name: The first_name of this CoreUserPT.
        :type: str
        """

        self._first_name = first_name

    @property
    def id(self):
        """
        Gets the id of this CoreUserPT.

        :return: The id of this CoreUserPT.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CoreUserPT.

        :param id: The id of this CoreUserPT.
        :type: int
        """

        self._id = id

    @property
    def imageurl(self):
        """
        Gets the imageurl of this CoreUserPT.

        :return: The imageurl of this CoreUserPT.
        :rtype: str
        """
        return self._imageurl

    @imageurl.setter
    def imageurl(self, imageurl):
        """
        Sets the imageurl of this CoreUserPT.

        :param imageurl: The imageurl of this CoreUserPT.
        :type: str
        """

        self._imageurl = imageurl

    @property
    def lang_key(self):
        """
        Gets the lang_key of this CoreUserPT.

        :return: The lang_key of this CoreUserPT.
        :rtype: str
        """
        return self._lang_key

    @lang_key.setter
    def lang_key(self, lang_key):
        """
        Sets the lang_key of this CoreUserPT.

        :param lang_key: The lang_key of this CoreUserPT.
        :type: str
        """

        self._lang_key = lang_key

    @property
    def last_name(self):
        """
        Gets the last_name of this CoreUserPT.

        :return: The last_name of this CoreUserPT.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """
        Sets the last_name of this CoreUserPT.

        :param last_name: The last_name of this CoreUserPT.
        :type: str
        """

        self._last_name = last_name

    @property
    def login(self):
        """
        Gets the login of this CoreUserPT.

        :return: The login of this CoreUserPT.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login):
        """
        Sets the login of this CoreUserPT.

        :param login: The login of this CoreUserPT.
        :type: str
        """

        self._login = login

    @property
    def network(self):
        """
        Gets the network of this CoreUserPT.

        :return: The network of this CoreUserPT.
        :rtype: CoreNetworkPT
        """
        return self._network

    @network.setter
    def network(self, network):
        """
        Sets the network of this CoreUserPT.

        :param network: The network of this CoreUserPT.
        :type: CoreNetworkPT
        """

        self._network = network

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CoreUserPT):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
