# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CrmTaskStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, name=None, network=None):
        """
        CrmTaskStatus - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'int',
            'name': 'str',
            'network': 'CorNetwork'
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'network': 'network'
        }

        self._id = id
        self._name = name
        self._network = network

    @property
    def id(self):
        """
        Gets the id of this CrmTaskStatus.

        :return: The id of this CrmTaskStatus.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this CrmTaskStatus.

        :param id: The id of this CrmTaskStatus.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this CrmTaskStatus.

        :return: The name of this CrmTaskStatus.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CrmTaskStatus.

        :param name: The name of this CrmTaskStatus.
        :type: str
        """

        self._name = name

    @property
    def network(self):
        """
        Gets the network of this CrmTaskStatus.

        :return: The network of this CrmTaskStatus.
        :rtype: CorNetwork
        """
        return self._network

    @network.setter
    def network(self, network):
        """
        Sets the network of this CrmTaskStatus.

        :param network: The network of this CrmTaskStatus.
        :type: CorNetwork
        """

        self._network = network

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CrmTaskStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
