# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SchTemplatePT(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, blocks=None, channel_id=None, id=None, name=None):
        """
        SchTemplatePT - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'blocks': 'list[SchBlockPT]',
            'channel_id': 'int',
            'id': 'int',
            'name': 'str'
        }

        self.attribute_map = {
            'blocks': 'blocks',
            'channel_id': 'channelId',
            'id': 'id',
            'name': 'name'
        }

        self._blocks = blocks
        self._channel_id = channel_id
        self._id = id
        self._name = name

    @property
    def blocks(self):
        """
        Gets the blocks of this SchTemplatePT.

        :return: The blocks of this SchTemplatePT.
        :rtype: list[SchBlockPT]
        """
        return self._blocks

    @blocks.setter
    def blocks(self, blocks):
        """
        Sets the blocks of this SchTemplatePT.

        :param blocks: The blocks of this SchTemplatePT.
        :type: list[SchBlockPT]
        """

        self._blocks = blocks

    @property
    def channel_id(self):
        """
        Gets the channel_id of this SchTemplatePT.

        :return: The channel_id of this SchTemplatePT.
        :rtype: int
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """
        Sets the channel_id of this SchTemplatePT.

        :param channel_id: The channel_id of this SchTemplatePT.
        :type: int
        """

        self._channel_id = channel_id

    @property
    def id(self):
        """
        Gets the id of this SchTemplatePT.

        :return: The id of this SchTemplatePT.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this SchTemplatePT.

        :param id: The id of this SchTemplatePT.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this SchTemplatePT.

        :return: The name of this SchTemplatePT.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this SchTemplatePT.

        :param name: The name of this SchTemplatePT.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) > 100:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `100`")
        if name is not None and len(name) < 0:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SchTemplatePT):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
