# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TraShuffleAdvertisementOptionalPT(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, offset_type=None, priority=None):
        """
        TraShuffleAdvertisementOptionalPT - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'offset_type': 'str',
            'priority': 'str'
        }

        self.attribute_map = {
            'offset_type': 'offsetType',
            'priority': 'priority'
        }

        self._offset_type = offset_type
        self._priority = priority

    @property
    def offset_type(self):
        """
        Gets the offset_type of this TraShuffleAdvertisementOptionalPT.

        :return: The offset_type of this TraShuffleAdvertisementOptionalPT.
        :rtype: str
        """
        return self._offset_type

    @offset_type.setter
    def offset_type(self, offset_type):
        """
        Sets the offset_type of this TraShuffleAdvertisementOptionalPT.

        :param offset_type: The offset_type of this TraShuffleAdvertisementOptionalPT.
        :type: str
        """

        self._offset_type = offset_type

    @property
    def priority(self):
        """
        Gets the priority of this TraShuffleAdvertisementOptionalPT.

        :return: The priority of this TraShuffleAdvertisementOptionalPT.
        :rtype: str
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """
        Sets the priority of this TraShuffleAdvertisementOptionalPT.

        :param priority: The priority of this TraShuffleAdvertisementOptionalPT.
        :type: str
        """

        self._priority = priority

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TraShuffleAdvertisementOptionalPT):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
