# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TraInvoicePT(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, customer=None, id=None, order=None, paid=None, payment_day=None, price=None, status=None):
        """
        TraInvoicePT - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'customer': 'TraCustomerPT',
            'id': 'int',
            'order': 'list[TraOrderPT]',
            'paid': 'bool',
            'payment_day': 'date',
            'price': 'float',
            'status': 'TraInvoiceStatus'
        }

        self.attribute_map = {
            'customer': 'customer',
            'id': 'id',
            'order': 'order',
            'paid': 'paid',
            'payment_day': 'paymentDay',
            'price': 'price',
            'status': 'status'
        }

        self._customer = customer
        self._id = id
        self._order = order
        self._paid = paid
        self._payment_day = payment_day
        self._price = price
        self._status = status

    @property
    def customer(self):
        """
        Gets the customer of this TraInvoicePT.

        :return: The customer of this TraInvoicePT.
        :rtype: TraCustomerPT
        """
        return self._customer

    @customer.setter
    def customer(self, customer):
        """
        Sets the customer of this TraInvoicePT.

        :param customer: The customer of this TraInvoicePT.
        :type: TraCustomerPT
        """

        self._customer = customer

    @property
    def id(self):
        """
        Gets the id of this TraInvoicePT.

        :return: The id of this TraInvoicePT.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TraInvoicePT.

        :param id: The id of this TraInvoicePT.
        :type: int
        """

        self._id = id

    @property
    def order(self):
        """
        Gets the order of this TraInvoicePT.

        :return: The order of this TraInvoicePT.
        :rtype: list[TraOrderPT]
        """
        return self._order

    @order.setter
    def order(self, order):
        """
        Sets the order of this TraInvoicePT.

        :param order: The order of this TraInvoicePT.
        :type: list[TraOrderPT]
        """

        self._order = order

    @property
    def paid(self):
        """
        Gets the paid of this TraInvoicePT.

        :return: The paid of this TraInvoicePT.
        :rtype: bool
        """
        return self._paid

    @paid.setter
    def paid(self, paid):
        """
        Sets the paid of this TraInvoicePT.

        :param paid: The paid of this TraInvoicePT.
        :type: bool
        """

        self._paid = paid

    @property
    def payment_day(self):
        """
        Gets the payment_day of this TraInvoicePT.

        :return: The payment_day of this TraInvoicePT.
        :rtype: date
        """
        return self._payment_day

    @payment_day.setter
    def payment_day(self, payment_day):
        """
        Sets the payment_day of this TraInvoicePT.

        :param payment_day: The payment_day of this TraInvoicePT.
        :type: date
        """

        self._payment_day = payment_day

    @property
    def price(self):
        """
        Gets the price of this TraInvoicePT.

        :return: The price of this TraInvoicePT.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """
        Sets the price of this TraInvoicePT.

        :param price: The price of this TraInvoicePT.
        :type: float
        """

        self._price = price

    @property
    def status(self):
        """
        Gets the status of this TraInvoicePT.

        :return: The status of this TraInvoicePT.
        :rtype: TraInvoiceStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this TraInvoicePT.

        :param status: The status of this TraInvoicePT.
        :type: TraInvoiceStatus
        """

        self._status = status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TraInvoicePT):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
