# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TraAdvertisementPT(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, customer_id=None, description=None, id=None, industry_id=None, media_item_id=None, name=None):
        """
        TraAdvertisementPT - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'customer_id': 'TraCustomerPT',
            'description': 'str',
            'id': 'int',
            'industry_id': 'ConfIndustryPT',
            'media_item_id': 'LibMediaItemPT',
            'name': 'str'
        }

        self.attribute_map = {
            'customer_id': 'customerId',
            'description': 'description',
            'id': 'id',
            'industry_id': 'industryId',
            'media_item_id': 'mediaItemId',
            'name': 'name'
        }

        self._customer_id = customer_id
        self._description = description
        self._id = id
        self._industry_id = industry_id
        self._media_item_id = media_item_id
        self._name = name

    @property
    def customer_id(self):
        """
        Gets the customer_id of this TraAdvertisementPT.

        :return: The customer_id of this TraAdvertisementPT.
        :rtype: TraCustomerPT
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """
        Sets the customer_id of this TraAdvertisementPT.

        :param customer_id: The customer_id of this TraAdvertisementPT.
        :type: TraCustomerPT
        """

        self._customer_id = customer_id

    @property
    def description(self):
        """
        Gets the description of this TraAdvertisementPT.

        :return: The description of this TraAdvertisementPT.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this TraAdvertisementPT.

        :param description: The description of this TraAdvertisementPT.
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """
        Gets the id of this TraAdvertisementPT.

        :return: The id of this TraAdvertisementPT.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this TraAdvertisementPT.

        :param id: The id of this TraAdvertisementPT.
        :type: int
        """

        self._id = id

    @property
    def industry_id(self):
        """
        Gets the industry_id of this TraAdvertisementPT.

        :return: The industry_id of this TraAdvertisementPT.
        :rtype: ConfIndustryPT
        """
        return self._industry_id

    @industry_id.setter
    def industry_id(self, industry_id):
        """
        Sets the industry_id of this TraAdvertisementPT.

        :param industry_id: The industry_id of this TraAdvertisementPT.
        :type: ConfIndustryPT
        """

        self._industry_id = industry_id

    @property
    def media_item_id(self):
        """
        Gets the media_item_id of this TraAdvertisementPT.

        :return: The media_item_id of this TraAdvertisementPT.
        :rtype: LibMediaItemPT
        """
        return self._media_item_id

    @media_item_id.setter
    def media_item_id(self, media_item_id):
        """
        Sets the media_item_id of this TraAdvertisementPT.

        :param media_item_id: The media_item_id of this TraAdvertisementPT.
        :type: LibMediaItemPT
        """

        self._media_item_id = media_item_id

    @property
    def name(self):
        """
        Gets the name of this TraAdvertisementPT.

        :return: The name of this TraAdvertisementPT.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this TraAdvertisementPT.

        :param name: The name of this TraAdvertisementPT.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TraAdvertisementPT):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
