# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.tra_invoice_pt import TraInvoicePT


class TestTraInvoicePT(unittest.TestCase):
    """ TraInvoicePT unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTraInvoicePT(self):
        """
        Test TraInvoicePT
        """
        model = swagger_client.models.tra_invoice_pt.TraInvoicePT()


if __name__ == '__main__':
    unittest.main()
