# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.channel_api import CHANNELApi


class TestCHANNELApi(unittest.TestCase):
    """ CHANNELApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.channel_api.CHANNELApi()

    def tearDown(self):
        pass

    def test_create_channel_using_post_using_post(self):
        """
        Test case for create_channel_using_post_using_post

        createChannel
        """
        pass

    def test_delete_channel_using_delete_using_delete(self):
        """
        Test case for delete_channel_using_delete_using_delete

        deleteChannel
        """
        pass

    def test_get_all_channels_using_get_using_get(self):
        """
        Test case for get_all_channels_using_get_using_get

        getAllChannels
        """
        pass

    def test_get_channel_using_get_using_get(self):
        """
        Test case for get_channel_using_get_using_get

        getChannel
        """
        pass

    def test_update_channel_using_put_using_put(self):
        """
        Test case for update_channel_using_put_using_put

        updateChannel
        """
        pass


if __name__ == '__main__':
    unittest.main()
