# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.crm_api import CRMApi


class TestCRMApi(unittest.TestCase):
    """ CRMApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.crm_api.CRMApi()

    def tearDown(self):
        pass

    def test_create_contact_activity_using_post_using_post(self):
        """
        Test case for create_contact_activity_using_post_using_post

        createContactActivity
        """
        pass

    def test_create_contact_using_post_using_post(self):
        """
        Test case for create_contact_using_post_using_post

        createContact
        """
        pass

    def test_create_customer_activity_using_post_using_post(self):
        """
        Test case for create_customer_activity_using_post_using_post

        createCustomerActivity
        """
        pass

    def test_create_customer_using_post_using_post(self):
        """
        Test case for create_customer_using_post_using_post

        createCustomer
        """
        pass

    def test_create_lead_activity_using_post_using_post(self):
        """
        Test case for create_lead_activity_using_post_using_post

        createLeadActivity
        """
        pass

    def test_create_lead_using_post_using_post(self):
        """
        Test case for create_lead_using_post_using_post

        createLead
        """
        pass

    def test_create_opportunity_activity_using_post_using_post(self):
        """
        Test case for create_opportunity_activity_using_post_using_post

        createOpportunityActivity
        """
        pass

    def test_create_opportunity_using_post_using_post(self):
        """
        Test case for create_opportunity_using_post_using_post

        createOpportunity
        """
        pass

    def test_get_all_contact_activities_using_get_using_get(self):
        """
        Test case for get_all_contact_activities_using_get_using_get

        getAllContactActivities
        """
        pass

    def test_get_all_contact_using_get_using_get(self):
        """
        Test case for get_all_contact_using_get_using_get

        getAllContact
        """
        pass

    def test_get_all_customer_activities_using_get_using_get(self):
        """
        Test case for get_all_customer_activities_using_get_using_get

        getAllCustomerActivities
        """
        pass

    def test_get_all_customers_using_get_using_get(self):
        """
        Test case for get_all_customers_using_get_using_get

        getAllCustomers
        """
        pass

    def test_get_all_lead_activities_using_get_using_get(self):
        """
        Test case for get_all_lead_activities_using_get_using_get

        getAllLeadActivities
        """
        pass

    def test_get_all_leads_using_get_using_get(self):
        """
        Test case for get_all_leads_using_get_using_get

        getAllLeads
        """
        pass

    def test_get_all_opportunities_using_get_using_get(self):
        """
        Test case for get_all_opportunities_using_get_using_get

        getAllOpportunities
        """
        pass

    def test_get_all_opportunity_activities_using_get_using_get(self):
        """
        Test case for get_all_opportunity_activities_using_get_using_get

        getAllOpportunityActivities
        """
        pass

    def test_get_contact_activity_using_get_using_get(self):
        """
        Test case for get_contact_activity_using_get_using_get

        getContactActivity
        """
        pass

    def test_get_contact_using_get_using_get(self):
        """
        Test case for get_contact_using_get_using_get

        getContact
        """
        pass

    def test_get_customer_activity_using_get_using_get(self):
        """
        Test case for get_customer_activity_using_get_using_get

        getCustomerActivity
        """
        pass

    def test_get_customer_using_get_using_get(self):
        """
        Test case for get_customer_using_get_using_get

        getCustomer
        """
        pass

    def test_get_lead_activity_using_get_using_get(self):
        """
        Test case for get_lead_activity_using_get_using_get

        getLead
        """
        pass

    def test_get_lead_using_get_using_get(self):
        """
        Test case for get_lead_using_get_using_get

        getLead
        """
        pass

    def test_get_opportunity_activity_using_get_using_get(self):
        """
        Test case for get_opportunity_activity_using_get_using_get

        getOpportunityActivity
        """
        pass

    def test_get_opportunity_using_get_using_get(self):
        """
        Test case for get_opportunity_using_get_using_get

        getOpportunity
        """
        pass

    def test_update_contact_activity_using_put_using_put(self):
        """
        Test case for update_contact_activity_using_put_using_put

        updateContactActivity
        """
        pass

    def test_update_contact_using_put_using_put(self):
        """
        Test case for update_contact_using_put_using_put

        updateContact
        """
        pass

    def test_update_customer_activity_using_put_using_put(self):
        """
        Test case for update_customer_activity_using_put_using_put

        updateCustomerActivity
        """
        pass

    def test_update_customer_using_put_using_put(self):
        """
        Test case for update_customer_using_put_using_put

        updateCustomer
        """
        pass

    def test_update_lead_activity_using_put_using_put(self):
        """
        Test case for update_lead_activity_using_put_using_put

        updateLeadActivity
        """
        pass

    def test_update_lead_using_put_using_put(self):
        """
        Test case for update_lead_using_put_using_put

        updateLead
        """
        pass

    def test_update_opportunity_activity_using_put_using_put(self):
        """
        Test case for update_opportunity_activity_using_put_using_put

        updateOpportunityActivity
        """
        pass

    def test_update_opportunity_using_put_using_put(self):
        """
        Test case for update_opportunity_using_put_using_put

        updateOpportunity
        """
        pass


if __name__ == '__main__':
    unittest.main()
