# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.library_api import LIBRARYApi


class TestLIBRARYApi(unittest.TestCase):
    """ LIBRARYApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.library_api.LIBRARYApi()

    def tearDown(self):
        pass

    def test_create_library_using_post_using_post(self):
        """
        Test case for create_library_using_post_using_post

        createLibrary
        """
        pass

    def test_delete_item_by_networ_shortcut_and_librar_using_delete_using_delete(self):
        """
        Test case for delete_item_by_networ_shortcut_and_librar_using_delete_using_delete

        deleteItemByNetworShortcutAndLibrar
        """
        pass

    def test_delete_library_using_delete_using_delete(self):
        """
        Test case for delete_library_using_delete_using_delete

        deleteLibrary
        """
        pass

    def test_get_all_items_by_networ_shortcut_and_library_prefix_using_get_using_get(self):
        """
        Test case for get_all_items_by_networ_shortcut_and_library_prefix_using_get_using_get

        getAllItemsByNetworShortcutAndLibraryPrefix
        """
        pass

    def test_get_all_libraries_using_get_using_get(self):
        """
        Test case for get_all_libraries_using_get_using_get

        getAllLibraries
        """
        pass

    def test_get_item_by_networ_shortcut_and_librar_using_get_using_get(self):
        """
        Test case for get_item_by_networ_shortcut_and_librar_using_get_using_get

        getItemByNetworShortcutAndLibrar
        """
        pass

    def test_get_library_using_get_using_get(self):
        """
        Test case for get_library_using_get_using_get

        getLibrary
        """
        pass

    def test_stream_item_by_networ_shortcut_and_librar_using_get_using_get(self):
        """
        Test case for stream_item_by_networ_shortcut_and_librar_using_get_using_get

        getItemStreamByNetworShortcutAndLibrar
        """
        pass

    def test_update_item_by_networ_shortcut_and_library_prefix_using_put_using_put(self):
        """
        Test case for update_item_by_networ_shortcut_and_library_prefix_using_put_using_put

        updateItemByNetworShortcutAndLibraryPrefix
        """
        pass

    def test_update_library_using_put_using_put(self):
        """
        Test case for update_library_using_put_using_put

        updateLibrary
        """
        pass

    def test_upload_items_by_networ_shortcut_and_library_prefix_using_post(self):
        """
        Test case for upload_items_by_networ_shortcut_and_library_prefix_using_post

        uploadItemsByNetworShortcutAndLibraryPrefix
        """
        pass


if __name__ == '__main__':
    unittest.main()
