# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.conf_industry_pt import ConfIndustryPT


class TestConfIndustryPT(unittest.TestCase):
    """ ConfIndustryPT unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfIndustryPT(self):
        """
        Test ConfIndustryPT
        """
        model = swagger_client.models.conf_industry_pt.ConfIndustryPT()


if __name__ == '__main__':
    unittest.main()
