# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.crm_opportunity_pt import CrmOpportunityPT


class TestCrmOpportunityPT(unittest.TestCase):
    """ CrmOpportunityPT unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrmOpportunityPT(self):
        """
        Test CrmOpportunityPT
        """
        model = swagger_client.models.crm_opportunity_pt.CrmOpportunityPT()


if __name__ == '__main__':
    unittest.main()
