# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.core_range_pt import CoreRangePT


class TestCoreRangePT(unittest.TestCase):
    """ CoreRangePT unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoreRangePT(self):
        """
        Test CoreRangePT
        """
        model = swagger_client.models.core_range_pt.CoreRangePT()


if __name__ == '__main__':
    unittest.main()
