# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.tra_discount import TraDiscount


class TestTraDiscount(unittest.TestCase):
    """ TraDiscount unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTraDiscount(self):
        """
        Test TraDiscount
        """
        model = swagger_client.models.tra_discount.TraDiscount()


if __name__ == '__main__':
    unittest.main()
