# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.lib_album_pt import LibAlbumPT


class TestLibAlbumPT(unittest.TestCase):
    """ LibAlbumPT unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLibAlbumPT(self):
        """
        Test LibAlbumPT
        """
        model = swagger_client.models.lib_album_pt.LibAlbumPT()


if __name__ == '__main__':
    unittest.main()
