# coding: utf-8

"""
    protone API

    protone API documentation

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.apiuserimpl_api import ApiuserimplApi


class TestApiuserimplApi(unittest.TestCase):
    """ ApiuserimplApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.apiuserimpl_api.ApiuserimplApi()

    def tearDown(self):
        pass

    def test_activate_account_using_get(self):
        """
        Test case for activate_account_using_get

        activateAccount
        """
        pass

    def test_change_password_using_post(self):
        """
        Test case for change_password_using_post

        changePassword
        """
        pass

    def test_finish_password_reset_using_post(self):
        """
        Test case for finish_password_reset_using_post

        finishPasswordReset
        """
        pass

    def test_get_account_using_get(self):
        """
        Test case for get_account_using_get

        getAccount
        """
        pass

    def test_is_authenticated_using_get(self):
        """
        Test case for is_authenticated_using_get

        isAuthenticated
        """
        pass

    def test_register_account_using_post(self):
        """
        Test case for register_account_using_post

        registerAccount
        """
        pass

    def test_request_password_reset_using_post(self):
        """
        Test case for request_password_reset_using_post

        requestPasswordReset
        """
        pass

    def test_save_account_using_post(self):
        """
        Test case for save_account_using_post

        saveAccount
        """
        pass


if __name__ == '__main__':
    unittest.main()
